name: zmoney
description: How Much?
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+38

environment:
  sdk: '>=3.1.0 <4.0.0'

dependency_overrides:
  http: ^1.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^4.0.0
  confetti: ^0.7.0
  shared_preferences: ^2.2.2
  
  path: ^1.8.0 # Check pub.dev for the latest version
  http: ^0.13.0
  translator: ^0.1.7
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.15.3
  animated_flip_counter: ^0.2.6
  marquee: ^2.2.3
  firebase_core: ^2.24.2
  oauth2: ^2.0.2
  windows_notification: ^1.0.0
  path_provider: ^2.1.1
  firebase_analytics: ^10.8.0
  firebase_analytics_web: ^0.5.5+12
  url_launcher: ^6.2.4
 
  firebase_ui_oauth: ^1.5.1
  games_services: ^4.0.1
  audioplayers: ^5.2.1
  intl: ^0.18.1
  firebase_performance: 0.9.3+17
  video_player: ^2.8.2
  flutter_appauth: ^6.0.4
  font_awesome_flutter: ^10.7.0
  firebase_ui_auth: ^1.13.0
  firebase_ui_oauth_google: ^1.3.0
  auto_localization: ^2.0.2
  plugin_platform_interface: ^2.0.0
  auto_size_text: ^3.0.0
  provider: ^6.1.2
  firebase_storage: ^11.6.8
  firebase_app_check: ^0.2.1+19
  in_app_purchase: ^3.1.13
  dio: ^5.4.1
  permission_handler: ^11.3.0

  animated_text_kit: ^4.2.2

  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_config:
  generate_for_dir: ["lib/"]
  env: ".env"
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/mainscreen.png
    - fonts/
  

  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/Proxima_Nova_Light.ttf
        - asset: fonts/Proxima_Nova_Light_It.ttf
          weight: 700
    - family: CartoonFont1
      fonts:
        - asset: fonts/arak.TTF
    - family: CartoonFont2
      fonts:
        - asset: fonts/bouncy.otf
    - family: CartoonFont3
      fonts:
        - asset: fonts/cheri.TTF 
    - family: CartoonFont4
      fonts:
        - asset: fonts/fof.ttf     
    - family: CartoonFont5
      fonts:
        - asset: fonts/grinched.otf 
    - family: CartoonFont6
      fonts:
        - asset: fonts/pork.TTF           
  # Add other configurations like assets and fonts as needed