name: zmoney
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+3

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^3.1.0
  confetti: ^0.7.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  windows_notification: ^0.0.3
  flutter_config: ^2.0.1
  flutter_appauth: ^6.0.2
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_config:
  generate_for_dir: ["lib/"]
  env: "/.env"

flutter:
  uses-material-design: true
  assets:
    - /.env

  # Add other configurations like assets and fonts as needed
