name: zmoney
description: How Much? Number Guessing Game
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 6.0.0+20

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^4.0.0
  confetti: ^0.7.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  
  
  
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.15.3
  animated_flip_counter: ^0.2.6
  marquee: ^2.2.3
  firebase_core: ^2.24.2
  oauth2: ^2.0.2
  windows_notification: ^1.0.0
  path_provider: ^2.1.1
  firebase_analytics: ^10.8.0
  firebase_analytics_web: ^0.5.5+12
  url_launcher: ^6.2.4
  games_services: ^4.0.0
  audioplayers: ^5.2.1
  intl: ^0.18.1
  firebase_performance: ^0.9.3+13
  video_player: ^2.8.2
  flutter_appauth: ^6.0.4
  font_awesome_flutter: ^10.7.0
  firebase_ui_auth: ^1.13.0
  firebase_ui_oauth_google: ^1.3.0
  flutter_facebook_auth: ^6.1.0
  firebase_ui_oauth_facebook: ^1.2.18
  barcode_widget: ^2.0.4
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_config:
  generate_for_dir: ["lib/"]
  env: ".env"
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/zmoneyblazing.png
    - assets/mainscreen.png
    - assets/sounds/victory_sound.mp3
    - assets/videos/main_video.mp4
    - assets/videos/8s.mp4
    - assets/
    # If you intend to include all assets within a directory, use this format:
    # - assets/

  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/Proxima_Nova_Light.ttf
        - asset: fonts/Proxima_Nova_Light_It.ttf
          weight: 700
  # Add other configurations like assets and fonts as needed