// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkoL2g9pI-JT4hXYU_3jUNcvfETl_leUA',
    appId: '1:446412900874:web:1ebc0c7a79621be627adf3',
    messagingSenderId: '446412900874',
    projectId: 'what-e7630',
    authDomain: 'what-e7630.firebaseapp.com',
    databaseURL: 'https://what-e7630-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'what-e7630.appspot.com',
    measurementId: 'G-0GNMPWT890',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-NeVmw7-vGAsfkP12KCX1nIo9hxwNyg',
    appId: '1:446412900874:android:0f97beb396296e6227adf3',
    messagingSenderId: '446412900874',
    projectId: 'what-e7630',
    databaseURL: 'https://what-e7630-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'what-e7630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzuk5hZDoWxblhtVb7Is3yhr_ibCnDkO0',
    appId: '1:446412900874:ios:0b41aec6f153545727adf3',
    messagingSenderId: '446412900874',
    projectId: 'what-e7630',
    databaseURL: 'https://what-e7630-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'what-e7630.appspot.com',
    androidClientId: '446412900874-alucfv888p73jk9eeqnbudlc0vnrtcl7.apps.googleusercontent.com',
    iosClientId: '446412900874-46um0p0g5vhj1jlfe5hn1lnchqmqpg4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.zmoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzuk5hZDoWxblhtVb7Is3yhr_ibCnDkO0',
    appId: '1:446412900874:ios:315a5900714eb9c827adf3',
    messagingSenderId: '446412900874',
    projectId: 'what-e7630',
    databaseURL: 'https://what-e7630-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'what-e7630.appspot.com',
    androidClientId: '446412900874-alucfv888p73jk9eeqnbudlc0vnrtcl7.apps.googleusercontent.com',
    iosClientId: '446412900874-00mjbe0crhbs1komf43pkfjhla1vfckf.apps.googleusercontent.com',
    iosBundleId: 'com.example.zmoney.RunnerTests',
  );
}
